version: "3"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'test1234'
      MYSQL_DATABASE: test
      MYSQL_USER: test-dev
      MYSQL_PASSWORD: 'test1234'